import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Navigation from "./layout/navigation";
import Footer from "./layout/footer";
import SocialsContainer from "./components/socialsContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Marius Jahn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      id="app"
      lang="en"
      className="h-full min-h-screen flex justify-center items-center dark"
    >
      <body className="h-full min-h-screen w-full flex items-center justify-center">
        <div className="sm:w-3/4 h-full min-h-screen flex flex-col">
          <Providers>
            <Navigation />
            <div className="px-6">{children}</div>
            <Footer />
          </Providers>
        </div>
        <SocialsContainer />
      </body>
    </html>
  );
}
